### ISSUE TITLE
Problem: dhcp_reservation and dhcp_subnet slow and inefficient

### ISSUE THREAD

**Issue by ptoal** [O-X-L/ansible-opnsense#235]
### Modules

- dhcp_subnet
- dhcp_reservation

### Version

```bash
1.2.14
```

### Ansible Version

```bash
ansible-core 2.16.14
```

### OPNSense Version

```bash
25.1.7_2
```

### OPNSense-Plugin Version

```bash

```

### Issue

Creating large numbers of subnets and reservations is really slow, and gets exponentially worse, the more reservations you have, due to the way that the plugin is querying every subnet, and every reservation in detail.

As you can see from the attached debug output, the more subnets (and the same for reservations), the more API calls happen every time you add a new reservation.

There must be a more efficient way to search for existing objects while adding, that doesn't require hitting the API once for every existing lease?

### Config Ansible

```yaml

```

### Config OPNSense

```bash

```

### Debug Output

```bash
*Creating first subnet*
[WARNING]: REQUEST: POST | URL: https://192.168.90.59/api/kea/dhcpv4/searchSubnet | HEADERS: '{'Content-Type': 'application/json'}' | DATA: '{"current": 1, "rowCount": 1000}'
[WARNING]: RESPONSE: '{'status_code': 200, '_request': <Request('POST', 'https://192.168.90.59/api/kea/dhcpv4/searchSubnet')>, '_num_bytes_downloaded': 46, '_elapsed':
datetime.timedelta(microseconds=121444), '_content': b'{"rows":[],"rowCount":0,"total":0,"current":1}'}'
[WARNING]: REQUEST: GET | URL: https://192.168.90.59/api/kea/dhcpv4/getSubnet
[WARNING]: RESPONSE: '{'status_code': 200, '_request': <Request('GET', 'https://192.168.90.59/api/kea/dhcpv4/getSubnet')>, '_num_bytes_downloaded': 471, '_elapsed':
datetime.timedelta(microseconds=81795), '_content': b'{"subnet4":{"subnet":"","next_server":"","option_data_autocollect":"1","option_data":{"domain_name_servers":{"":{"value":"","selected":1}},"d
omain_search":{"":{"value":"","selected":1}},"routers":{"":{"value":"","selected":1}},"static_routes":"","domain_name":"","ntp_servers":{"":{"value":"","selected":1}},"time_servers":{"":{"value":
"","selected":1}},"tftp_server_name":"","boot_file_name":"","v6_only_preferred":""},"match-client-id":"1","pools":"","description":""}}'}'
[WARNING]: REQUEST: POST | URL: https://192.168.90.59/api/kea/dhcpv4/addSubnet | HEADERS: '{'Content-Type': 'application/json'}' | DATA: '{"subnet4": {"subnet": "192.168.1.0/24", "description":
"", "pools": "192.168.1.200-192.168.1.224", "option_data_autocollect": 0, "option_data": {"domain_name_servers": "192.168.1.3,192.168.1.1", "routers": "192.168.1.1", "static_routes": "",
"domain_name": "test1", "tftp_server_name": "", "boot_file_name": "", "ntp_servers": "", "time_servers": "", "domain_search": ""}}}'
[WARNING]: RESPONSE: '{'status_code': 200, '_request': <Request('POST', 'https://192.168.90.59/api/kea/dhcpv4/addSubnet')>, '_num_bytes_downloaded': 64, '_elapsed':
datetime.timedelta(microseconds=86857), '_content': b'{"result":"saved","uuid":"59ded287-0800-4f7a-848f-357a62f6ab2b"}'}'


*Creating Second Subnet*
[WARNING]: RESPONSE: '{'status_code': 200, '_request': <Request('POST', 'https://192.168.90.59/api/kea/dhcpv4/searchSubnet')>, '_num_bytes_downloaded': 261, '_elapsed':
datetime.timedelta(microseconds=118097), '_content':
b'{"rows":[{"uuid":"59ded287-0800-4f7a-848f-357a62f6ab2b","subnet":"192.168.1.0\\/24","next_server":"","option_data_autocollect":"0","option_data":"","match-client-
id":"1","pools":"192.168.1.200-192.168.1.224","description":""}],"rowCount":1,"total":1,"current":1}'}'
[WARNING]: REQUEST: GET | URL: https://192.168.90.59/api/kea/dhcpv4/getSubnet/59ded287-0800-4f7a-848f-357a62f6ab2b
[WARNING]: RESPONSE: '{'status_code': 200, '_request': <Request('GET', 'https://192.168.90.59/api/kea/dhcpv4/getSubnet/59ded287-0800-4f7a-848f-357a62f6ab2b')>, '_num_bytes_downloaded': 613,
'_elapsed': datetime.timedelta(microseconds=67396), '_content': b'{"subnet4":{"subnet":"192.168.1.0\\/24","next_server":"","option_data_autocollect":"0","option_data":{"domain_name_servers":{"192
.168.1.3":{"value":"192.168.1.3","selected":1},"192.168.1.1":{"value":"192.168.1.1","selected":1}},"domain_search":{"":{"value":"","selected":1}},"routers":{"192.168.1.1":{"value":"192.168.1.1","
selected":1}},"static_routes":"","domain_name":"test1","ntp_servers":{"":{"value":"","selected":1}},"time_servers":{"":{"value":"","selected":1}},"tftp_server_name":"","boot_file_name":"","v6_onl
y_preferred":""},"match-client-id":"1","pools":"192.168.1.200-192.168.1.224","description":""}}'}'
[WARNING]: NOT MATCHING: '192.168.1.0/24' != '192.168.2.0/24'
[WARNING]: REQUEST: POST | URL: https://192.168.90.59/api/kea/dhcpv4/addSubnet | HEADERS: '{'Content-Type': 'application/json'}' | DATA: '{"subnet4": {"subnet": "192.168.2.0/24", "description":
"", "pools": "192.168.2.200-192.168.2.224", "option_data_autocollect": 0, "option_data": {"domain_name_servers": "192.168.1.3,192.168.1.1", "routers": "192.168.2.1", "static_routes": "",
"domain_name": "test2", "tftp_server_name": "", "boot_file_name": "", "ntp_servers": "", "time_servers": "", "domain_search": ""}}}'
[WARNING]: RESPONSE: '{'status_code': 200, '_request': <Request('POST', 'https://192.168.90.59/api/kea/dhcpv4/addSubnet')>, '_num_bytes_downloaded': 64, '_elapsed':
datetime.timedelta(microseconds=83243), '_content': b'{"result":"saved","uuid":"578e3509-50a2-4d8f-815f-1550f31939b9"}'}'

*Creating Third Subnet*
[WARNING]: RESPONSE: '{'status_code': 200, '_request': <Request('POST', 'https://192.168.90.59/api/kea/dhcpv4/searchSubnet')>, '_num_bytes_downloaded': 477, '_elapsed':
datetime.timedelta(microseconds=125343), '_content':
b'{"rows":[{"uuid":"59ded287-0800-4f7a-848f-357a62f6ab2b","subnet":"192.168.1.0\\/24","next_server":"","option_data_autocollect":"0","option_data":"","match-client-id":"1","pools":"192.168.1.200-
192.168.1.224","description":""},{"uuid":"578e3509-50a2-4d8f-815f-1550f31939b9","subnet":"192.168.2.0\\/24","next_server":"","option_data_autocollect":"0","option_data":"","match-client-
id":"1","pools":"192.168.2.200-192.168.2.224","description":""}],"rowCount":2,"total":2,"current":1}'}'
[WARNING]: RESPONSE: '{'status_code': 200, '_request': <Request('GET', 'https://192.168.90.59/api/kea/dhcpv4/getSubnet/59ded287-0800-4f7a-848f-357a62f6ab2b')>, '_num_bytes_downloaded': 613,
'_elapsed': datetime.timedelta(microseconds=66334), '_content': b'{"subnet4":{"subnet":"192.168.1.0\\/24","next_server":"","option_data_autocollect":"0","option_data":{"domain_name_servers":{"192
.168.1.3":{"value":"192.168.1.3","selected":1},"192.168.1.1":{"value":"192.168.1.1","selected":1}},"domain_search":{"":{"value":"","selected":1}},"routers":{"192.168.1.1":{"value":"192.168.1.1","
selected":1}},"static_routes":"","domain_name":"test1","ntp_servers":{"":{"value":"","selected":1}},"time_servers":{"":{"value":"","selected":1}},"tftp_server_name":"","boot_file_name":"","v6_onl
y_preferred":""},"match-client-id":"1","pools":"192.168.1.200-192.168.1.224","description":""}}'}'
[WARNING]: REQUEST: GET | URL: https://192.168.90.59/api/kea/dhcpv4/getSubnet/578e3509-50a2-4d8f-815f-1550f31939b9
[WARNING]: RESPONSE: '{'status_code': 200, '_request': <Request('GET', 'https://192.168.90.59/api/kea/dhcpv4/getSubnet/578e3509-50a2-4d8f-815f-1550f31939b9')>, '_num_bytes_downloaded': 613,
'_elapsed': datetime.timedelta(microseconds=66089), '_content': b'{"subnet4":{"subnet":"192.168.2.0\\/24","next_server":"","option_data_autocollect":"0","option_data":{"domain_name_servers":{"192
.168.1.3":{"value":"192.168.1.3","selected":1},"192.168.1.1":{"value":"192.168.1.1","selected":1}},"domain_search":{"":{"value":"","selected":1}},"routers":{"192.168.2.1":{"value":"192.168.2.1","
selected":1}},"static_routes":"","domain_name":"test2","ntp_servers":{"":{"value":"","selected":1}},"time_servers":{"":{"value":"","selected":1}},"tftp_server_name":"","boot_file_name":"","v6_onl
y_preferred":""},"match-client-id":"1","pools":"192.168.2.200-192.168.2.224","description":""}}'}'
[WARNING]: NOT MATCHING: '192.168.1.0/24' != '192.168.3.0/24'
[WARNING]: NOT MATCHING: '192.168.2.0/24' != '192.168.3.0/24'
[WARNING]: REQUEST: POST | URL: https://192.168.90.59/api/kea/dhcpv4/addSubnet | HEADERS: '{'Content-Type': 'application/json'}' | DATA: '{"subnet4": {"subnet": "192.168.3.0/24", "description":
"", "pools": "192.168.3.200-192.168.3.224", "option_data_autocollect": 0, "option_data": {"domain_name_servers": "192.168.1.3,192.168.1.1", "routers": "192.168.3.1", "static_routes": "",
"domain_name": "test3", "tftp_server_name": "", "boot_file_name": "", "ntp_servers": "", "time_servers": "", "domain_search": ""}}}'
[WARNING]: RESPONSE: '{'status_code': 200, '_request': <Request('POST', 'https://192.168.90.59/api/kea/dhcpv4/addSubnet')>, '_num_bytes_downloaded': 64, '_elapsed':
datetime.timedelta(microseconds=85418), '_content': b'{"result":"saved","uuid":"7ca3af7f-585b-466a-83fe-726b94d24559"}'}'
```

### Profiling Output

```bash

```

**Comment by superstes** [comment]
Related to:
- https://github.com/O-X-L/ansible-opnsense/pull/233
  There is an issue with a recent API change
- https://github.com/O-X-L/ansible-opnsense/issues/185
  We have implemented some 'multi' modules to optimize the way data is fetched (once instead of for every single entry)
  But we've not yet had time to implement it for newer modules.. 😕

**Comment by ptoal** [comment]
Ah, thanks.  I understand what's going on, now.  I agree that #185 is very valuable.

Are these two issues being actively worked on?  I'm happy to contribute, though I'm still getting familiar with the codebase, so would need some pointers on where to focus the effort, and what the desired design pattern is

**Comment by superstes** [comment]
I've started some work on it: https://github.com/O-X-L/ansible-opnsense/pull/236
Still some way to go though..

**Comment by superstes** [comment]
Should be fixed when #236 is done - but it might still take some week/a month or so.

**Comment by superstes** [comment]
Update: The abstracted multi-version handling was finally merged into latest.
More info can be found here: https://github.com/O-X-L/ansible-opnsense/issues/185
